## Escribiendo fórmulas ópticas para lentes gruesas

In [32]:
def foco(n,R1,R2,d):
    f_ = ( n*R1*R2 )/( n*(d+R2-R1) - d )
    f = f_/(n-1)
    return f

## 1. Analizando la lente-córnea

### 1.1 Longitud focal y puntos nodales de la córnea

In [33]:
def cornea(onda_nm):
    
    R1 = 7.8
    R2 = 6.7
    th = 0.5
    n = 1.
    
    if onda_nm == '400':
        n = 1.3898
    elif onda_nm == '550':
        n = 1.3774
    elif onda_nm == '700':
        n = 1.3730
        
    focal = foco(n,R1,R2,th)
    
    h1 = -1.*focal*(n-1)*th/(n*R2)
    
    h2 = -1.*focal*(n-1)*th/(n*R1)

    return focal,h1,h2,n,R1,R2,th

In [34]:
f_c,h1_c,h2_c,n_c,R1_c,R2_c,th_c = cornea('400')
print("Longitud focal de la cornea (mm): ", f_c)
print("Distancia a la superficie 1 de la córnea (mm): ",h1_c)
print("Distancia a la superficie 2 de la córnea (mm): ",h2_c)
print("Distancia a la superficie 2 de la córnea (mm): ",n_c)

Longitud focal de la cornea (mm):  -139.68929229523854
Distancia a la superficie 1 de la córnea (mm):  2.9238012414909895
Distancia a la superficie 2 de la córnea (mm):  2.5114702971781577
Distancia a la superficie 2 de la córnea (mm):  1.3898


In [35]:
print(n_c)

1.3898


## 2. Analizando la lente-aqueous

In [36]:
def aqueous(onda_nm):
    
    R1 = 6.7
    R2 = 10.0
    th = 3.0
    n = 1.
    
    if onda_nm == '400':
        n = 1.3515
    elif onda_nm == '550':
        n = 1.3388
    elif onda_nm == '700':
        n = 1.3343
        
    focal = foco(n,R1,R2,th)
    
    h1 = -1.*focal*(n-1)*th/(n*R2)
    
    h2 = -1.*focal*(n-1)*th/(n*R1)
    
    return focal,h1,h2,n,R1,R2,th

In [37]:
f_a,h1_a,h2_a,n_a,R1_a,R2_a,th_a = aqueous('400')
print("Longitud focal del arqueous (mm): ", f_a)
print("Distancia a la superficie 1 del arqueous (mm): ",h1_a)
print("Distancia a la superficie 2 del arqueous (mm): ",h2_a)

Longitud focal del arqueous (mm):  46.715749403090946
Distancia a la superficie 1 del arqueous (mm):  -3.644969126567473
Distancia a la superficie 2 del arqueous (mm):  -5.440252427712646


## 3. Analizando el lente-cristalino(lens)

In [38]:
def lens(onda_nm):
    
    R1 = 10.0
    R2 = -6.0
    th = 4.0
    n = 1.
    
    if onda_nm == '400':
        n = 1.4387
    elif onda_nm == '550':
        n = 1.4218
    elif onda_nm == '700':
        n = 1.4162
        
    focal = foco(n,R1,R2,th)
    
    h1 = -1.*focal*(n-1)*th/(n*R2)
    
    h2 = -1.*focal*(n-1)*th/(n*R1)
    
    return focal,h1,h2,n,R1,R2,th

In [39]:
f_l,h1_l,h2_l,n_l,R1_l,R2_l,th_l = lens('400')
print("Longitud focal del cristalino (mm): ", f_l)
print("Distancia a la superficie 1 del cristalino (mm): ",h1_l)
print("Distancia a la superficie 2 del cristalino (mm): ",h2_l)

Longitud focal del cristalino (mm):  9.25338701385485
Distancia a la superficie 1 del cristalino (mm):  1.8810782340437537
Distancia a la superficie 2 del cristalino (mm):  -1.1286469404262522


### 4. Matrices de transferencia 

#### 4.1 M.T para espacio con índice de refracción n

In [40]:
import numpy as np

In [41]:
A = np.array([[2, 3], [1, -1]])
B = np.array([[1, 2], [0, -3]])
print(A)
print(B)
print(np.dot(A,B))

[[ 2  3]
 [ 1 -1]]
[[ 1  2]
 [ 0 -3]]
[[ 2 -5]
 [ 1  5]]


In [42]:
#todas las matrices en mm

In [43]:
def matriz_espacio(onda_nm,distancia,medio='aire'):
    
    if onda_nm == '400':
        n_v = 1.3494
        n_a = 1.3515
    elif onda_nm == '550':
        n_v = 1.3374
        n_a = 1.3388
    elif onda_nm == '700':
        n_v = 1.3331
        n_a = 1.3343
        
    if medio == 'aire':
        n = 1.
    elif medio == 'aqueous':
        n = n_a
    elif medio == 'vitreous':
        n = n_v
        
    M = np.array([[1,distancia/n],[0,1]])
    return M            

In [44]:
ME = matriz_espacio('400',6000) #en el aire
print(ME)

[[1.e+00 6.e+03]
 [0.e+00 1.e+00]]


In [45]:
MA = matriz_espacio('400',3,'aqueous') #en el AQUEOUS
print(MA)

[[1.         2.21975583]
 [0.         1.        ]]


In [46]:
MV = matriz_espacio('400',16.6,'vitreous') #en el VITREOUS
print(MV)

[[ 1.         12.30176375]
 [ 0.          1.        ]]


#### 4.2 M.T para lente gruesa con índice de refracción n

In [47]:
MA = matriz_lente('400','aqueous')
print(MA)

[[ 0.88354565  2.21975583]
 [-0.02140606  1.07802442]]


In [48]:
MM

array([[ 7.38794601e-01,  4.43807505e+03],
       [-1.06083480e-01, -6.35909421e+02]])

### Corrección de miopia

In [49]:
## matrices

In [50]:
M1 = np.array([[1,6000],[0,1]])
print(M1)

[[   1 6000]
 [   0    1]]


In [51]:
M2 = np.array([[1,0],[(1-n_c)/abs(R1_c),1]])
print(M2)

[[ 1.          0.        ]
 [-0.04997436  1.        ]]


In [52]:
M3 = np.array([[1,th_c/(n_c)],[0,1]])
print(M3)

[[1.         0.35976399]
 [0.         1.        ]]


In [53]:
M4 = np.array([[1,0],[(n_c-n_a)/abs(R2_c),1]])
print(M4)

[[1.         0.        ]
 [0.00571642 1.        ]]


In [54]:
M5 = np.array([[1,th_a/(n_a)],[0,1]])
print(M5)

[[1.         2.21975583]
 [0.         1.        ]]


In [55]:
M6 = np.array([[1,0],[(n_a-n_l)/abs(R1_l),1]])
print(M6)

[[ 1.       0.     ]
 [-0.00872  1.     ]]


In [56]:
M7 = np.array([[1,th_l/(n_l)],[0,1]])
print(M7)

[[1.         2.78028776]
 [0.         1.        ]]


In [57]:
n_v = 1.3494
M8 = np.array([[1,0],[-1*(n_l-n_v)/abs(R2_l),1]])
print(M8)

[[ 1.          0.        ]
 [-0.01488333  1.        ]]


In [58]:
MMM = M8@M7@M6@M5@M4@M3@M2@M1
print(MMM)

[[ 7.38794601e-01  4.43807505e+03]
 [-6.30610080e-02 -3.77465517e+02]]


In [59]:
B = MMM[0][1]
D = MMM[1][1]

-1.*(B*n_v)/D

15.865657117104533

In [60]:
1/D

-0.002649248619145772

In [61]:
SO=M8@M7@M6@M5@M4@M3@M2

In [62]:
SO

array([[ 0.7387946 ,  5.30744164],
       [-0.06306101,  0.90053092]])

In [63]:
-1./a21

9.426538397167228

In [64]:
a11=SO[0][0]
a12=SO[0][1]
a21=SO[1][0]
a22=SO[1][1]
print(a12)

5.307441641497943


In [65]:
nt=1.3494
fi=-1.*nt/a21
print(fi)

21.398325885806752


In [66]:
V1H1 = (a22-1)/a21
print(V1H1)

1.5773468439954579


In [67]:
V2H2 = nt*(1-a11)/(a21)
print(V2H2)

-5.589358254007225


In [68]:
fi+V2H2

15.808967631799527

In [69]:
f0=1./a21
print(f0)

-15.857659615982476


In [71]:
abs(f0)-V1H1

14.280312771987017